language: r

sudo: required
dist: trusty

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - LINTR_COMMENT_BOT=false

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      - libmagick++-dev
      - wget
      - libatlas3gf-base
      - libatlas-dev
      - python-joblib
      - python-dev
      - libv8-dev

before_install:
  - pip install --user numpy
  - pip install --user 'tensorflow==1.7'

r_packages:
  - devtools
  - lintr
  - reticulate
  - testthat
  - covr
  - rmarkdown
  - coda
  - R6
  - DiagrammeR
  - knitr
  - rsvg
  - bayesplot
  - extraDistr
  - tensorflow
  - greta

r_github_packages:
  - rich-iannone/DiagrammeRsvg

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
