language: r
sudo: required
dist: trusty

cache: packages

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - LINTR_COMMENT_BOT=false

r_packages:
  - devtools
  - covr
  - testthat
  - lintr

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
