language: r

sudo: required
dist: trusty

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - LINTR_COMMENT_BOT=false

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda create -y -n r-tensorflow python=3.6 tensorflow-probability==0.5.0  
  - source activate r-tensorflow

r_packages:
  - devtools
  - lintr
  - reticulate
  - testthat
  - covr
  - rmarkdown
  - coda
  - R6
  - DiagrammeR
  - knitr
  - rsvg
  - bayesplot
  - extraDistr
  - tensorflow
  
r_github_packages:
  - greta-dev/greta


after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
